ignoreGeneratedHeader = false
severity = "warning"
confidence = 0.8
errorCode = 1
warningCode = 1

[rule.blank-imports]
[rule.identical-branches]
[rule.context-as-argument]
[rule.context-keys-type]
[rule.dot-imports]
[rule.error-return]
[rule.error-strings]
[rule.error-naming]
[rule.errorf]
[rule.get-return]
[rule.exported]
[rule.increment-decrement]
[rule.var-naming]
[rule.var-declaration]
[rule.range]
[rule.receiver-naming]
[rule.time-naming]
[rule.unexported-return]
[rule.indent-error-flow]
[rule.if-return]
[rule.empty-block]
[rule.empty-lines]
[rule.import-shadowing]
[rule.superfluous-else]
[rule.unused-parameter]
[rule.unreachable-code]
[rule.redefines-builtin-id]
[rule.early-return]
[rule.nested-structs]
[rule.optimize-operands-order]
[rule.range-val-address]
[rule.string-of-int]
[rule.struct-tag]
[rule.time-date]
[rule.time-equal]
[rule.unconditional-recursion]
[rule.unnecessary-stmt]
[rule.use-errors-new]
[rule.useless-break]
[rule.waitgroup-by-value]

[rule.enforce-map-style]
arguments = ["literal"]

[rule.function-result-limit]
arguments = [3]
